from .simple_serializers import SimpleUserSerializer, SimpleEmpresaSerializer
from .carrito_compra_viewset import CarritoCompraSerializer, CarritoCompraViewSet
from .carrito_producto_viewset import CarritoProductoSerializer, CarritoProductoViewSet
from .suscripcion_empresa_viewset import SuscripcionEmpresaViewSet, SuscripcionEmpresaSerializer
from .compra_viewset import CompraSerializer, CompraViewSet
from .producto_viewset import ProductoSerializer, ProductoViewSet
from .noticia_viewset import NoticiaSerializer, NoticiaViewSet
from .empresa_viewset import EmpresaSerializer, EmpresaViewSet
from .metodo_pago_viewset import MetodoPagoSerializer, MetodoPagoViewSet
from .newsletter_viewset import NewsletterSerializer, NewsletterViewSet
from .usuario_viewset import UsuarioSerializer, UsuarioViewSet
from .user_viewset import UserSerializer, UserViewSet

