# Generated by Django 5.0.4 on 2024-11-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0002_noticia_comentarionoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_expiracion', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('es_visa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='Access.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Access.metodopago'),
        ),
    ]
