# Generated by Django 5.0.4 on 2024-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0003_metodopago_compra_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionempresa',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
