# Generated by Django 5.0.4 on 2024-11-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0004_suscripcionempresa_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
